---
# tasks file for provision
- block:
  - include_vars: ../ovirt_Password.yml

  - name: Obtain SSO token using username/password creds.
    ovirt_auth:
      url: "https://{{ rhev_manager_host }}/ovirt-engine/api"
      username: "{{ ovirt_username }}"
      ca_file: ../pki-resource.cer
      insecure: yes
      password: "{{ ovirt_password }}"

    # Create the hosts_file data model
  - include_tasks: construct_hosts_dict.yml

  - name: Provisioning a single machine
    include_tasks: single_provision.yml
    when: single_machine | bool

  - name: Provisioning a sequence of machines
    include_tasks: sequence_provision.yml
    when: not (single_machine | bool)

  - name: Clear the hosts_file dictionary ready for next run
    set_fact:
      hosts_file: {}

  always:
  - name: Always revoke the SSO token
    ovirt_auth:
      state: absent
      ovirt_auth: "{{ ovirt_auth }}"

