---
# tasks file for provision
- block:
  - include_vars: ../ovirt_Password.yml

  - name: Obtain SSO token using username/password creds.
    ovirt_auth:
      url: https://rhvm.internal.croftvillas.com/ovirt-engine/api
      username: admin@internal
      ca_file: ../pki-resource.cer
      password: "{{ ovirt_password }}"

  - name: Check if the machine already exists
    ovirt_vm_facts:
      auth: "{{ ovirt_auth }}"
      pattern: name="{{ hostname_prefix[0] }}.{{ cluster_name }}.internal.croftvillas.com"

  - block:
    - block:
      - name: Create a disk for the new VM
        ovirt_disk:
          auth: "{{ ovirt_auth }}"
          name: "{{ hostname_prefix[0] }}_{{ cluster_name }}_disk"
          size: "{{ disk_size }}GiB"
          storage_domain: QNAP_SD
          interface: virtio
        register: new_disks


      - name: Create a RHCOS machine to boot off of the pre-install ignition
        ovirt_vm:
          auth: "{{ ovirt_auth }}"
          cluster: "Cluster01"
          name: "{{ hostname_prefix[0] }}.{{ cluster_name }}.internal.croftvillas.com"
          description: "{{ cluster_name }} {{node_type}}"
          comment: "{{ cluster_name }}"
          state: running
          memory: "{{ host_memory }}GiB"
          cpu_sockets: "{{ sockets }}"
          kernel_path: "iso://rhcos-{{ cluster_version }}-x86_64-installer-kernel"
          initrd_path: "iso://rhcos-{{ cluster_version }}-x86_64-installer-initramfs.img"
          kernel_params: "nomodeset rd.neednet=1 coreos.inst=yes coreos.inst.install_dev=vda coreos.inst.image_url=http://{{ gateway }}/rhcos-{{ cluster_version }}-x86_64-metal-bios.raw.gz coreos.inst.ignition_url=http://{{ gateway }}/{{ cluster_name }}/{{ node_type }}.ign"
          kernel_params_persist: yes
          fetch_nested: true
          nested_attributes:
            - mac
          graphical_console:
            protocol: vnc
          type: server
          operating_system: "rhel_8x64"
          disks:
            - name: "{{ hostname_prefix[0] }}_{{ cluster_name }}_disk"
          nics:
            - name: nic1
              profile_name: "ovirtmgmt"
        register: new_vms
      - name: extract the mac address of the newly created machine
        set_fact:
          mac_address: "{{ new_vms.vm.nics[0].mac.address }}"
      when: machine_type == "rhcos"

    - block:
      - name: Clones a machine from a rhel7 template
        ovirt_vm:
          auth: "{{ ovirt_auth }}"
          state: running
          cluster: "Cluster01"
          name: "{{ hostname_prefix[0] }}.{{ cluster_name }}.internal.croftvillas.com"
          description: "{{ cluster_name }} {{node_type}}"
          comment: "{{ cluster_name }}"
          template: rhel7_template
          fetch_nested: true
          nested_attributes:
            - mac
          wait: True
          memory: "{{ host_memory }}GiB"
          cpu_sockets: "{{ sockets }}"
          graphical_console:
            protocol: vnc
          cloud_init:
            host_name: "{{ hostname_prefix[0] }}.{{ cluster_name }}.internal.croftvillas.com"
            authorized_ssh_keys: "{{ ssh_key }}"
        register: new_vms
      - name: Extract the mac address of the newly created machine
        set_fact:
          mac_address: "{{ new_vms.vm.nics[0].mac.address }}"
      when: machine_type == "rhel"



    - name: Get DHCP leases from the ClearOS Gateway API
      uri:
        url: "https://{{ gateway }}:81/api/v1/dhcp/leases"
        return_content: yes
        headers:
           x-api-key: "{{ apikey }}"
      register: leases

    - name: Print out the leases
      debug:
        var: leases
        verbosity: 1

    - name: Find the IP address given to the machine by ClearOS Gateway DHCP
      set_fact:
        iface_address: "{{ leases.json.data | dict2items | json_query(query)}}"
      vars:
        query: "[].{mac: value.mac ipv4: value.ip}[?mac == '{{ mac_address }}'].ipv4"

    - name: Print out the discovered IP address
      debug:
        msg: "{{ iface_address[0] }}"
        verbosity: 1

    - name: Print out information about the newly created machine
      debug:
        var: new_vms
        verbosity: 1

    - name: Loop over the hostname_prefix list and construct a line for the /etc/hosts file
      set_fact:
        the_line: "{{ the_line|default([]) + [ item + '.' + cluster_name + '.internal.croftvillas.com' ] }}"
      with_items:
        - "{{ hostname_prefix }}"

    - name: Add the hosts file line to the ClearOS Gateway
      lineinfile:
        line: "{{ iface_address[0] }} {{ the_line | join(' ') }}"
        dest: /etc/hosts
        state: present
      remote_user: root
      delegate_to: "{{ gateway }}"

    - name: Re-initialise the hosts variable ready for the next run
      set_fact:
        the_line: []

    - name: Restart dnsmasq on ClearOS Gateway to make sure the added host is picked up in DNS
      systemd:
        name: dnsmasq
        state: restarted
      remote_user: root
      delegate_to: "{{ gateway }}"

    - name: Remove the kernel boot parameters from the newly created machine
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        cluster: "Cluster01"
        name: "{{ hostname_prefix[0] }}.{{ cluster_name }}.internal.croftvillas.com"
        state: running
        type: server
        wait: yes
        timeout: 300
        kernel_path: ""
        initrd_path: ""
        kernel_params: ""
        kernel_params_persist: yes
      when: machine_type == "rhcos"
    when: not ovirt_vms | length | bool

  # at this stage the host should be created so make sure it is in the inventory
  - name: Add the new hosts into the in memory inventory for use in haproxy configuration
    add_host:
      name: "{{ hostname_prefix[0] }}.{{ cluster_name }}.internal.croftvillas.com"
      groups: "{{ node_type }}"

  always:
  - name: Always revoke the SSO token
    ovirt_auth:
      state: absent
      ovirt_auth: "{{ ovirt_auth }}"

