# tasks file for provision
- name: <Multiple Machines> Check if the machines already exists
  ovirt_vm_facts:
    auth: "{{ ovirt_auth }}"
    pattern: name="{{ hostname_prefix[0] }}*.{{ cluster_name }}.internal.croftvillas.com"

- name: <Multiple Machines> Set fact with machine existence
  set_fact:
    machine_exists: ovirt_vms | length

- block:
  - name: <Multiple Machines> Asynchronously create the disks wait for them to finish
    include_tasks: create_disk_async.yml

  - name: <Multiple Machines> Asynchronously create machines and move on
    include_tasks: create_rhcos_async.yml

  - name: <Multiple Machines> Write DNS entries into dnsmasq hosts file
    include_tasks: write_dns_entries.yml

  - name: <Multiple Machines> Remove the kernel boot parameters from the newly created machine
    ovirt_vm:
      auth: "{{ ovirt_auth }}"
      cluster: "Cluster01"
      name: "{{ hostname_prefix[0] }}{{ item }}.{{ cluster_name }}.{{ domain_name }}"
      state: running
      type: server
      wait: no
      kernel_path: ""
      initrd_path: ""
      kernel_params: ""
      kernel_params_persist: yes
    with_sequence: start="{{ sequence_start }}" end="{{ sequence_end }}" format="%01d"
  when: not machine_exists | bool




