---
- name: This is a playbook for cloning a vm in RHEV
  hosts: localhost
  gather_facts: False
  vars:
    gateway: gateway.internal.croftvillas.com
    machine_state: present
    host_memory: 8
#    hostname_prefix: rhel
    sockets: 2
    disk_size: 8

  tasks:
    - block:
      - include_vars: ../ovirt_Password.yml
      
      - name: Obtain SSO token using username/password creds.
        ovirt_auth:
          url: https://rhvm.internal.croftvillas.com/ovirt-engine/api
          username: admin@internal
          ca_file: ../pki-resource.cer
          password: "{{ ovirt_password }}"

      - name: Add an additional disk to the VM
        ovirt_disk:
          auth: "{{ ovirt_auth }}"
          name: "{{ hostname_prefix }}_disk"
          size: "{{ disk_size }}GiB"
          storage_domain: QNAP_SD
          interface: virtio
        register: new_disks
    

      - name: This task clones a machine in RHEV
        ovirt_vm:
          auth: "{{ ovirt_auth }}"
          cluster: "Cluster01"
          name: "{{ hostname_prefix }}.ocp4.internal.croftvillas.com"
          description: ocp4 worker
          comment: ocp4
          state: running
          memory: "{{ host_memory }}GiB"
          cpu_sockets: "{{ sockets }}"
          kernel_path: "iso://rhcos-410.8.20190509.3-installer-kernel"
          initrd_path: "iso:///rhcos-410.8.20190509.3-installer-initramfs.img"
          kernel_params: "nomodeset rd.neednet=1 coreos.inst=yes coreos.inst.install_dev=vda coreos.inst.image_url=http://gateway/rhcos-uefi.gz coreos.inst.ignition_url=http://gateway/worker.ign"
          kernel_params_persist: yes
          fetch_nested: true
          nested_attributes:
            - mac
          graphical_console:
            protocol: vnc
          bios_type: "q35_ovmf"
          type: server
          operating_system: "rhel_8x64"
          disks:
            - name: "{{ hostname_prefix }}_disk"
          nics:
            - name: nic1
              profile_name: "ovirtmgmt"
        register: new_vms

      - name: extract the mac address of the newly created machine
        set_fact:
          mac_address: "{{ new_vms.vm.nics[0].mac.address }}"

      - name: Get leases from Gateway API
        uri:
          url: "https://{{ gateway }}:81/api/v1/dhcp/leases"
          return_content: yes
          headers:
             x-api-key: "{{ apikey }}"
        register: leases

      - name: Debug the this variable
        debug:
          var: leases
          verbosity: 1

      - name: find the IP address given to the machine from DHCP
        set_fact:
          iface_address: "{{ leases.json.data | dict2items | json_query(query)}}"
        vars:
          query: "[].{mac: value.mac ipv4: value.ip}[?mac == '{{ mac_address }}'].ipv4"



      - name: Debug the this variable
        debug:
          msg: "{{ iface_address[0] }}"
          verbosity: 1

      - name: Debug created machine
        debug:
          var: new_vms
          verbosity: 1

      - name: make sure that the hostname is added to the dnsmasq hosts file
        lineinfile:
          line: "{{ iface_address[0] }} {{ hostname_prefix }}.ocp4.internal.croftvillas.com"
          dest: /etc/hosts
          state: present
        remote_user: root
        delegate_to: "{{ gateway }}"

      - name: Restart DNS masq
        systemd:
          name: dnsmasq
          state: restarted
        remote_user: root
        delegate_to: "{{ gateway }}"

      - name: Start up machine hopefully it will get hostname from dhcp
        ovirt_vm:
          auth: "{{ ovirt_auth }}"
          cluster: "Cluster01"
          name: "{{ hostname_prefix }}.ocp4.internal.croftvillas.com"
          state: next_run
          wait: yes
          kernel_path: ""
          initrd_path: ""
          kernel_params: ""
          kernel_params_persist: yes
          bios_type: "q35_ovmf"

      - name: Add the new host into the inventory
        add_host: hostname={{ hostname_prefix }}.ocp4.internal.croftvillas.com


      always:
      - name: Always revoke the SSO token
        ovirt_auth:
          state: absent
          ovirt_auth: "{{ ovirt_auth }}"

- name: Playbook to install guest agent on new machine
  hosts: "{{ hostname_prefix }}.ocp4.internal.croftvillas.com"
  become: yes
  remote_user: core

  vars:
    guest_agent: "http://rpmfind.net/linux/centos/7.6.1810/os/x86_64/Packages/qemu-guest-agent-2.12.0-2.el7.x86_64.rpm"

  tasks:

      - name: Install the guest agent on the new node
        command: "rpm-ostree install --idempotent {{ guest_agent }}"

      - name: Reboot new host
        reboot:



