  # Now that all the machines have been provisioned we can configure haproxy (validation of the config will fail if machines are not set up correctly)
- name: Install and configure haproxy
  hosts: "haproxy.{{ cluster_name }}.internal.croftvillas.com"
  remote_user: root

  roles:
      # Role to install haproxy and configure it for the openshift cluster - requires in memory inventory from provisioning play above
    - haproxy_configure
