# Refactored the plays into imports so that we can construct a workflow in Tower
- import_playbook: bootstrap.yml
- import_playbook: cluster.yml
- import_playbook: haproxy.yml
- import_playbook: worker.yml
- import_playbook: haproxy.yml
- import_playbook: guest_agent.yml
- import_playbook: finalise.yml
