# Refactored the plays into imports so that we can construct a workflow in Tower

# Install and configure haproxy to that bootstrap will be ready to go
- import_playbook: haproxy.yml

# Install and boot the bootstrap server
- import_playbook: bootstrap.yml

# Add Bootstrap into the load balancer
- import_playbook: haproxy.yml

# Provision the masters
- import_playbook: master.yml

# Provision the workers
- import_playbook: worker.yml

# Add the workers into the load balancer
- import_playbook: haproxy.yml

# Install and boot the bootstrap server
- import_playbook: bootstrap_run.yml

# All hosts are up, bootstrap is complete - install the qemu guest agent
# And reboot the servers
# - import_playbook: guest_agent.yml

# Finalise the install, remove the bootstrap server, reload the
# load balancer and wait for install scripts to complete
# Finally print the kubeadmin and kubeconfig to stdout so we can
# Connect to our server
- import_playbook: finalise.yml
