- name: While bootstrap is running provision the workers and the wait for bootstrap to complete
  hosts: localhost
  gather_facts: False

  roles:
    - role: provision
      single_machine: False
      sequence_start: 0
      sequence_end: 1
      host_memory: 8
      sockets: 2
      disk_size: 40
      node_type: worker
      machine_type: rhcos
      hostname_prefix:
        - worker0
