---
# tasks file for decommission
- block:
  - include_vars: ../ovirt_Password.yml

  - name: Obtain SSO token using username/password creds.
    ovirt_auth:
      url: "https://{{ rhev_manager_host }}/ovirt-engine/api"
      username: "{{ ovirt_username }}"
      ca_file: ../pki-resource.cer
      insecure: yes
      password: "{{ ovirt_password }}"

  - name: Check if the machine already exists
    ovirt_vm_facts:
      auth: "{{ ovirt_auth }}"
      fetch_nested: true
      nested_attributes:
        - mac
      pattern: name="{{ hostname_prefix[0] }}.{{ cluster_name }}.{{ domain_name }}"

  - name: <Single Machine> Set fact with machine existence
    set_fact:
      machine_exists: "{{ ovirt_vms | length > 0 }}"


  # Conditional Block only runs when machine exists
  - block:
    - name: Decommission the machine from RHV
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        cluster: "Cluster01"
        name: "{{ hostname_prefix[0] }}.{{ cluster_name }}.{{ domain_name }}"
        state: absent

    - name: extract the mac address of the newly created machine
      set_fact:
        mac_address: "{{ ovirt_vms[0].nics[0].mac.address }}"

    - name: Get the DHCP leases from the ClearOS Gateway
      uri:
        url: "https://{{ gateway }}:81/api/v1/dhcp/leases"
        return_content: yes
        validate_certs: no
        headers:
           x-api-key: "{{ apikey }}"
      register: leases

    - name: Find the IP address given to the machine from DHCP
      set_fact:
        iface_address: "{{ leases.json.data | dict2items | json_query(query)}}"
      vars:
        query: "[].{mac: value.mac ipv4: value.ip}[?mac == '{{ mac_address }}'].ipv4"

    - name: Construct the /etc/hosts file line for the decommissioned server
      set_fact:
        the_line: "{{ the_line|default([]) + [ item + '.' + cluster_name + '.' + domain_name ] }}"
      with_items:
        - "{{ hostname_prefix }}"

    - name: Remove the host line from /etc/hosts file on the ClearOS Gateway server
      lineinfile:
        line: "{{ iface_address[0] }} {{ the_line | join(' ') }}"
        dest: /etc/hosts
        state: absent
      remote_user: root
      delegate_to: "{{ gateway }}"

    - name: Reset the hosts variable ready for the next run
      set_fact:
        the_line: []

    - name: Restart DNS masq on the ClearOS Gateway to make sure the changes are in DNS
      systemd:
        name: dnsmasq
        state: restarted
      remote_user: root
      delegate_to: "{{ gateway }}"

    when: machine_exists | bool

  always:
  - name: Always revoke the SSO token
    ovirt_auth:
      state: absent
      ovirt_auth: "{{ ovirt_auth }}"

