---
- name: This is a playbook for cloning a vm in RHEV
  hosts: localhost
  gather_facts: False

  roles:
    - role: provision
      host_memory: 2
      sockets: 1
      node_type: load balancer
      machine_type: rhel
      hostname_prefix:
        - haproxy
        - api
        - api-int

    - role: provision
      host_memory: 16
      sockets: 4
      disk_size: 8
      node_type: bootstrap
      machine_type: rhcos
      hostname_prefix:
        - bootstrap

    - role: provision
      host_memory: 16
      sockets: 4
      disk_size: 8
      node_type: master
      machine_type: rhcos
      hostname_prefix:
        - master00
        - etcd-0

    - role: provision
      host_memory: 16
      sockets: 4
      disk_size: 8
      node_type: master
      machine_type: rhcos
      hostname_prefix:
        - master01
        - etcd-1

    - role: provision
      host_memory: 16
      sockets: 4
      disk_size: 8
      node_type: master
      machine_type: rhcos
      hostname_prefix:
        - master02
        - etcd-2


- name: Subscribe to RHN and install haproxy
  hosts: "haproxy.{{ cluster_name }}.internal.croftvillas.com"
  become: yes

  roles:
    - haproxy_configure


